### ISSUE TITLE
Ability to edit and delete transfers

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/asset-apps#1]
Use v-drawer similar to asset_owner

**Comment by klondikemarlen** [comment]
Additional Details:
Tranfer.vue
- Filtering by condition starting with `REQUEST:`.

TransferEditor (supports delete)

TransferApprover
- If condition starts with `REQUEST:` the user needs an "approve request" button instead of "save"

**Comment by klondikemarlen** [comment]
When `asset_transfer` is tagged (asset_item_id is present) -> can't edit the tag or description
When `asset_transfer` has a "category" (asset_category_id), they change the "category"
`asset_transfer.description` can never be changed
