### ISSUE TITLE
Don't allow 'Unknown' Owner selectable by end-users

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/asset-apps#17]
We want people to use their correct owner record rather than allowing them to be lazy and select "Unknown".

**Comment by klondikemarlen** [comment]
@datajohnson Is there a specific view that needs to be tweaked? Or should `Unknown` be removed from all UI selectors?
Current locations where it is used are:
- `web/src/components/AssetEditor.vue`
- `web/src/components/AssetEditorLimited.vue`
- `web/src/components/AssetTagSidebar.vue`
- `web/src/store/index.js`
- `web/src/views/Administration/Home.vue`
- `web/src/views/Manage/List.vue`

Additionally, can the lists of
- `web/src/components/AssetEditor.vue`
- `web/src/components/AssetEditorLimited.vue`
- `web/src/views/Administration/Home.vue`
- `web/src/views/Manage/List.vue`
be replaced with the list in `web/src/store/index.js`?
Originals are:
```

**Comment by datajohnson** [comment]
I got a bit more clarification on this from Rob:

Unknown will still own some assets, but we can't let end-users select it - Administrators can in their screens though. Basically it comes down to two components circled in green - just filter out `mailcode == "Unknown"`. Over time, the Unknown owned assets will disappear through attrition and we will completely delete that owner record.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/346325/156091029-63c4057a-1831-43c2-ba28-216bcb9d5831.png">

**Comment by datajohnson** [comment]
Additionally, completely remove the card/controls marked in orange Xs above to clean up crap from the Dashboard.
