### ISSUE TITLE
After Tag Request workflow...

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/asset-apps#27]
- Send an email to the person who requested the tags
 - Send an email to `assets@yukon.ca` 

Both emails need to contain the list of generated tags `YXXXXXXX`

Michael will finalize the wording and email formats after this is done in conjunction with client.

**Comment by klondikemarlen** [comment]
There are two separate emails:
1) to the user who requested which sends the tag_request_complete.html with a link to go and add more data to the tags.
2) to the [assets@yukon.ca](mailto:assets@yukon.ca) basically letting them know they need to get busy on the printer tag_request_notify.html
