### ISSUE TITLE
Add Ability to Revert a Completed Transfer

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/asset-apps#35]
# User Story
1. When an admin reverts a transfer, the status of the associated asset is set back to "Active" and the asset regains its original owner.
2. When an admin accepts a requested transfer (i.e. a transfer with condition REQUEST: xxxx) it sets the asset owner to the requested owner.

# Details
If the transfer is for a tagged asset:
 - The `asset_item.asset_owner_id` on the asset record is assigned back to the asset_transfer.from_owner_id from the transfer
 - The `asset_item.status` is be changed to "Active"

**Comment by klondikemarlen** [comment]
Sort of an abort -> rollback operation.
