### ISSUE TITLE
Finish wiring up Tag Request on /dashboard

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/asset-apps#8]
Needs to generate unique 'YXXXXXX' numbers for the tag, record the owner, insert row(s) into `tblTestTagRepeat`. The format of that table is CRAP but it's legacy and currently hooked up to the printer, so we can't change it. Not all fields are required in there, but 

 - YTG_NUMBER
 - Mailcode

are the big ones and fill in any other we have data for based on the request.

It should then email someone (likely Rob, but I'll get that figured out and into the .env.sample)

We will give the requestor access to come back and add the metadata similar to the hard-coded current workflow. We will email a link (`/asset-tags/recent`) to the requestor that shows them the newly generated 'YXXXXXX' numbers.

**Comment by datajohnson** [comment]
Additionally, that Tag Request component is pulling in mailcodes and it needs to be switched to owners instead - long story

**Comment by klondikemarlen** [comment]
Component that needs to be edited is: `web/src/components/AssetRegisterForm.vue`
Current has no back-end wiring; needs to write data to the `tblTestTagRepeat`
There is no need to feed the data back to the `web/src/views/MyTags.vue` component at this time.

Will need a sequence for the Y number.

1. Generate unique Y number.
2. Create an item in the `asset_item` minimal record information that we currently have.
3. Insert Y number into `tblTestTagRepeat` and whatever information we have.

**Comment by klondikemarlen** [comment]
Future information:
- asset_item -> purchase_person == req.user.email
- MyTags table will be filtered by email.
